### PR TITLE
Fix ZodError when description is missing in presence data

### LINKED ISSUE #1028: Student orgs
It seems like there is an issue involving a `ZodError` that is caused by a missing or undefined `description` field, which is expected to be a `string`. This issue occurs in the `fetchOrg` function located in the `source/student-orgs/presence.ts` file on line 62.

### Detailed Insights:
1. The first error log contains the following details:
   - **Error Type**: `ZodError`
   - **Cause**: The `description` field is expected to be a string, but the code encountered `undefined`.
   - **Affected Code**:
     - `get error` (line 39 in `node_modules/zod/v3/types.js`)
     - `ZodIntersection.parse` (line 114 in `node_modules/zod/v3/types.js`)
     - `fetchOrg` (line 62 in `source/student-orgs/presence.ts`)

2. HTTP Requests:
   - A series of `GET` requests to APIs under the `https://api.presence.io/stolaf/v1/organizations/` path are logged.
   - These requests appear to succeed (`status_code: 200`), implying that the API responses themselves are likely not malformed.
   - The issue seems to arise within the processing or validation of these responses rather than the HTTP requests.

### Recommendation:
1. **Validation and Debugging**:
   - Review the `fetchOrg` function implementation.
   - Check the API response payloads for the `description` field and ensure all expected fields are present.
   - Add debugging logs before the validation step to log the raw API responses.

2. **Error Handling**:
   - Adjust the logic in `fetchOrg` to handle cases where the `description` might be missing or `undefined`. Depending on the context, either:
     - Assign a default value for `description` when it is undefined.
     - Log a clear error message if `description` is missing in the API response.

3. **Zod Schema**:
   - If possible, revise the Zod schema to make `description` optional (`z.string().optional()`), if it is not strictly required.
   - Alternatively, provide a fallback mechanism when `description` is missing.

---

The `fetchOrg` function fetches data from an API endpoint and attempts to validate the response using the `DetailedPresenceOrgSchema`:

```typescript
const fetchOrg = async (base: string, orgUri: string) =>
  DetailedPresenceOrgSchema.parse(await getJson(`${base}/${orgUri}`));
```

### Sources of the Issue
1. **Validation Error**:
   - The `DetailedPresenceOrgSchema` requires a `description` field of the `string` type.
   - If the fetched data does not include this field or has it as `undefined`, this results in the `ZodError`.

2. **API Response Handling**:
   - The API at the constructed URL `{base}/{orgUri}` is likely missing the `description` field.

### Suggested Fix
1. **Ensure API Contract**:
   - Confirm that the `description` field is always included in the API response.
   - If the `description` can legitimately be missing, adjust the schema validation to make it optional:
     ```typescript
     description: z.string().optional(),
     ```

2. **Add Error Handling**:
   - Handle validation errors gracefully and log incomplete or invalid records for debugging:
     ```typescript
     const fetchOrg = async (base: string, orgUri: string) => {
       try {
         return DetailedPresenceOrgSchema.parse(await getJson(`${base}/${orgUri}`));
       } catch (error) {
         console.error(`Error fetching org at ${orgUri}:`, error);
         return null; // Or handle as needed
       }
     };
     ```

3. **Default Fallbacks**:
   - If a default empty value for `description` is acceptable, it can be supplied in the data transformation logic:
     ```typescript
     const description = org.description ?? "No description available";
     ```

### PR DESCRIPTION
**Pull request by rye**
- Fixes #1028.
- Closes #1029 
- Closes #1031

### CODE REVIEW

File: source/student-orgs/presence.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ const BasicPresenceOrgSchema = z.object({
 type DetailedPresenceOrgType = z.infer<typeof DetailedPresenceOrgSchema>
 const DetailedPresenceOrgSchema = BasicPresenceOrgSchema.and(
 	z.object({
-		description: z.string(),
+		description: z.string().nullish().default(''),
```
Comment (hawkrives) [inline source/student-orgs/presence.ts]: does this work when the field is missing entirely from the Presence response?

**Review by drewvolz — DISMISSED** [review]
